"""multi-language support

Revision ID: 051a0b132864
Revises: 478b031cc771
Create Date: 2024-10-24 18:15:14.599557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '051a0b132864'
down_revision: Union[str, None] = '478b031cc771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages'))
    )
    op.create_index(op.f('ix_languages_name'), 'languages', ['name'], unique=False)
    op.add_column('blog_articles', sa.Column('language_id', sa.Integer(), nullable=True))
    op.add_column('blog_articles', sa.Column('translation_of_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_blog_articles_language_id'), 'blog_articles', ['language_id'], unique=False)
    op.create_index(op.f('ix_blog_articles_translation_of_id'), 'blog_articles', ['translation_of_id'], unique=False)
    op.create_foreign_key(op.f('fk_blog_articles_language_id_languages'), 'blog_articles', 'languages', ['language_id'], ['id'])
    op.create_foreign_key(op.f('fk_blog_articles_translation_of_id_blog_articles'), 'blog_articles', 'blog_articles', ['translation_of_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_blog_articles_translation_of_id_blog_articles'), 'blog_articles', type_='foreignkey')
    op.drop_constraint(op.f('fk_blog_articles_language_id_languages'), 'blog_articles', type_='foreignkey')
    op.drop_index(op.f('ix_blog_articles_translation_of_id'), table_name='blog_articles')
    op.drop_index(op.f('ix_blog_articles_language_id'), table_name='blog_articles')
    op.drop_column('blog_articles', 'translation_of_id')
    op.drop_column('blog_articles', 'language_id')
    op.drop_index(op.f('ix_languages_name'), table_name='languages')
    op.drop_table('languages')
    # ### end Alembic commands ###
