"""product reviews

Revision ID: d4d9dedcf45c
Revises: 0d50af9054c5
Create Date: 2024-10-21 14:28:57.337443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d9dedcf45c'
down_revision: Union[str, None] = '0d50af9054c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_reviews',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_product_reviews_customer_id_customers')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_reviews_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'customer_id', name=op.f('pk_product_reviews'))
    )
    op.create_index(op.f('ix_product_reviews_timestamp'), 'product_reviews', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_reviews_timestamp'), table_name='product_reviews')
    op.drop_table('product_reviews')
    # ### end Alembic commands ###
